name: Build Chess Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up g++
      run: sudo apt update && sudo apt install -y g++

    - name: Build project
      run: |
        g++ -std=c++17 \
          src/main.cpp \
          src/board/Board.cpp \
          src/data/DatabaseManager.cpp \
          src/pieces/King.cpp \
          src/pieces/Queen.cpp \
          src/pieces/Rook.cpp \
          src/pieces/Bishop.cpp \
          src/pieces/Knight.cpp \
          src/pieces/Pawn.cpp \
          -lsqlite3 -o chess


    - name: Skip running interactive app
      run: echo "Skipping runtime for now — interactive app"


